project_id = "totalscope-intelligence"

[api]
enabled = true
port = 55431
schemas = ["public", "graphql_public"]

[db]
port = 55432
major_version = 15

[studio]
enabled = true
port = 55433

[local_smtp]
enabled = true
port = 55434
smtp_port = 55435
pop3_port = 55436

[analytics]
enabled = true
port = 55437
backend = "postgres"

[auth]
enabled = true
site_url = "http://localhost:3000"
