import type { VisionScreen } from "@/lib/product-vision/model";
const s=(id: number,section:VisionScreen["section"],title:string,question:string,status:VisionScreen["status"],template:VisionScreen["template"],message:string,highlights:string[],persona?:string):VisionScreen=>({id,section,title,question,status,template,message,highlights,persona});
export const PRODUCT_VISION_SCREENS:readonly VisionScreen[]=[
s(1,"Why TSI exists","Welcome to TotalScope Intelligence","What opportunity can operational data unlock?","Vision Preview","hero","TotalScope Intelligence converts operational data into actionable business intelligence.",["Run TotalScope better","Deliver measurable intelligence to clients","Create proprietary roofing-industry data products"]),
s(2,"Why TSI exists","The current problem","Why is valuable information still hard to use?","Vision Preview","sources","The information already exists, but leadership should not have to manually calculate, compare, reconcile, or interpret it.",["TotalScope application data","Notes and documents","Monday exports","Stripe and invoices","Assignments and outcomes","Client activity"]),
s(3,"Why TSI exists","The Intelligence Pipeline","How does raw information become executive confidence?","Live Foundation + Future Vision","pipeline","C3 establishes governed facts, the Analytics Engine, KPIs, and operational dashboards—the foundation for every future layer.",["Raw Source Data","Canonical Facts","Analytics Engine","KPIs","Observations","Recommendations","Executive Intelligence Reports","Ask TSI"]),
s(4,"Internal TotalScope","Taylor’s Monday morning","Where do I need to focus today?","Live C3 Feature","dashboard","Executive attention begins with operational fires, not a wall of statistics.",["New files · 6","Active files · 3","Completed files · 3","Stalled files · 1","Aging files · 2","Limited financial data · 2"],"Taylor — Operations"),
s(5,"Internal TotalScope","Breson’s financial view","What financial value did we create, and what was collected?","Live C3 Foundation","financial","Approved, traceable outcomes connect settlement value, charges, collections, and exceptions.",["Settlement gain · $12,500","Approved charges · $1,690","Net client gain · $10,046","ROI · 594%","Collected · $1,690","Refunds · $100","Processor fees · $58"],"Breson — Finance and Executive Leadership"),
s(6,"Internal TotalScope","Client health","Which clients are healthy, declining, inactive, or requiring attention?","Vision Preview","client-health","Client health is explained through contributing facts—not hidden behind an unexplained score.",["Submission consistency","Operational friction","Financial value","Branch performance","Data limitations"]),
s(7,"Internal TotalScope","Claim-handler performance","Who performs best for specific carriers and operating conditions?","Live C3 Foundation + Vision Preview","handlers","Counts remain visible while comparative conclusions require a qualifying cohort.",["Completed files","Active workload","Average cycle time","Median cycle time","Settlement gain","Minimum comparative cohort · 10"]),
s(8,"Internal TotalScope","Data Health","Can we trust what we are seeing?","Live C3 Feature","data-health","TSI does not merely report data. It identifies when the data should not yet be trusted.",["Imports completed · 2","Records reconciled · 67","Financial coverage · 83%","Missing dates · 1","Unmatched financial · 0","KPI availability · 97%"]),
s(9,"Internal TotalScope","Summit Roofing Group","What work and value support this client relationship?","Live C3 Foundation","client-detail","A client-level review connects branches, outcomes, carrier mix, and every supporting file.",["Branches · 2","Files · 4","Active / completed · 2 / 2","Settlement gain · $6,500","Approved charges · $1,090","Net gain · $5,410"]),
s(10,"Internal TotalScope","Individual file traceability","What facts support this material result?","Live C3 Foundation","file-detail","Every material result can be traced back to the file and source facts that support it.",["File · TSI-1001","Client · Summit Roofing Group","Carrier · North Star Mutual","Status · Completed","Initial · $10,000","Final · $14,000","Gain · $4,000","Fee · $300"]),
s(11,"Client experience","Client executive overview","What value is TotalScope creating for our company?","Vision Preview","client-portal","Now viewing: Client Portal — Summit Roofing Group",["Files submitted · 38","Active files · 64","Completed this quarter · 91","Settlement gains · $428,600","Fees paid · $31,900","Net client benefit · $396,700","ROI · 1,243%"]),
s(12,"Client experience","Active work","What is progressing, blocked, or waiting on us?","Vision Preview","active-work","A positive, transparent view of current work without emphasizing predicted charges.",["In estimating · 18","Actively handled · 24","Awaiting carrier · 9","Client action required · 4","Nearing completion · 11","Aging files · 7"]),
s(13,"Client experience","Completed outcomes","Which completed files produced measurable value?","Vision Preview","outcomes","Completed outcomes connect carrier movement, paid fees, and client benefit to the underlying file.",["SRG-26041 · $18,400 increase","SRG-26038 · $12,650 increase","SRG-26029 · $9,800 increase"]),
s(14,"Client experience","Trends and benchmarking","How are our branches and carriers changing over time?","Vision Preview","benchmarks","Client-owned trends remain distinct from responsibly anonymized peer benchmarks.",["Monthly submission volume","Average settlement gain","Average turnaround time","Branch comparison","Carrier response patterns","Anonymized peer benchmarks"]),
s(15,"Client experience","Executive Intelligence Report","What should leadership know and do this month?","Vision Preview","report","A concise monthly leadership brief combines outcomes, attention items, trends, observations, and recommended actions.",["Executive summary","Financial value created","Completed outcomes","Files requiring attention","Trends and observations","Recommended actions"]),
s(16,"Client subscriptions","Subscription plans","How could TSI become recurring client value?","Illustrative Business Model","pricing","TSI can become a recurring-revenue product layered on top of TotalScope’s existing services.",["Essential · qualifying volume or $99/mo","Professional · $299/mo","Enterprise · $750–$1,500/mo"]),
s(17,"Client subscriptions","Recurring-revenue example","What could illustrative adoption produce?","Illustrative Business Model","revenue","This scenario demonstrates potential business-model scale and is not a forecast.",["50 Essential × $99 · $4,950/mo","40 Professional × $299 · $11,960/mo","10 Enterprise × $1,000 · $10,000/mo","Illustrative MRR · $26,910","Illustrative ARR · $322,920"]),
s(18,"Client subscriptions","Strategic value beyond subscriptions","How else does client intelligence strengthen TotalScope?","Vision Preview","value","Client intelligence can deepen the relationship while making TotalScope easier to understand and harder to replace.",["Client retention","Submission volume","Sales differentiation","Account reviews","Enterprise acquisition","Renewal conversations","Trust and transparency"]),
s(19,"Industry intelligence","State of the Roofing Industry","What proprietary perspective could governed aggregate data create?","Vision Preview","report-cover","The State of Roofing Claims and Restoration — 2027 Industry Intelligence Report",["Claim-volume trends","Initial and final settlements","Claim uplift","Carrier response times","Disputed categories","Seasonal trends","Operational benchmarks"]),
s(20,"Industry intelligence","External report pricing","Who might buy industry intelligence, and how?","Illustrative Business Model","market-pricing","All external products require approved privacy, aggregation, contractual, and legal policies.",["Digital report · $995","Company license · $2,500","Enterprise license · $10,000+","Regional analysis · $7,500+","Benchmark subscription · $5,000–$25,000"]),
s(21,"Industry intelligence","Additional intelligence products","Which adjacent data products could TSI support?","Vision Preview","products","Responsibly governed, anonymized intelligence can serve a market beyond existing TotalScope clients.",["Regional market reports","Carrier scorecards","Contractor benchmarking","Storm-response intelligence","Industry outlook","Supplier reports","PE due diligence","Custom research"]),
s(22,"Future of TSI","Automated observations","What changed, and why does it matter?","Future Capability","observations","Deterministic observations surface material changes without pretending to make business decisions.",["Three branches accounted for 71% of this month’s submission decline.","A qualifying State Farm cohort closed materially faster.","Failed-payment volume increased for a second consecutive week."]),
s(23,"Future of TSI","Recommendations","What action should leadership consider next?","Future Capability","recommendations","Recommendations translate governed evidence into clearly qualified operating choices.",["Route qualifying State Farm claims to Julie when capacity permits.","Contact Harbor Roofing; submissions are below its trailing range.","Review three failed payments representing $4,620."]),
s(24,"Future of TSI","Ask TSI","How can leaders explore governed data conversationally?","Future Capability","ask","A conversational layer can answer questions while retaining metric definitions, permissions, and source traceability.",["Which clients stopped submitting files?","Which handlers close State Farm claims fastest?","What caused last month’s revenue decline?","Which files produced the highest ROI?","Where is data unreliable?"]),
s(25,"Future of TSI","The TotalScope Intelligence vision","Where does the platform go from here?","Product Vision","closing","TotalScope Intelligence begins by helping us run TotalScope better. It evolves into a client-facing subscription platform and ultimately into a proprietary source of roofing-industry intelligence.",["Internal Intelligence","Client Intelligence","Subscription Revenue","Industry Intelligence"])
] as const;
export const PRODUCT_VISION_SECTIONS=[...new Set(PRODUCT_VISION_SCREENS.map(x=>x.section))];
