import type { VisionScreen } from "@/lib/product-vision/model";
const s=(id: number,section:VisionScreen["section"],title:string,question:string,status:VisionScreen["status"],template:VisionScreen["template"],message:string,highlights:string[],persona?:string):VisionScreen=>({id,section,title,question,status,template,message,highlights,persona});
export const PRODUCT_VISION_SCREENS:readonly VisionScreen[]=[
s(1,"Why TSI exists","Welcome to TotalScope Intelligence","What opportunity can operational data unlock?","Vision Preview","hero","TotalScope Intelligence converts operational data into actionable business intelligence.",["Run TotalScope better","Deliver measurable intelligence to clients","Create proprietary roofing-industry data products"]),
s(2,"Why TSI exists","The current problem","Why is valuable information still hard to use?","Vision Preview","sources","Six systems each tell part of the story. Leadership still spends Monday morning reconciling exports, notes, payments, assignments, and client activity by hand.",["Application data · 1,284 active files without one executive view","Notes & documents · 8,412 updates separated from outcomes","Monday exports · 4,281 rows across disconnected boards","Stripe & invoices · 37 exceptions outside operating workflows","Assignments · 19 handoffs with unclear ownership","Client activity · 3 declining branches found after month-end"]),
s(3,"Why TSI exists","From fragmented signals to one executive brief","How does TSI turn scattered activity into leadership action?","Live Foundation + Future Vision","pipeline","TSI automatically reconciles weather, JobNimbus, Monday, notes, payments, and documents—then explains stalled work, client trends, financial exceptions, and the actions leadership should consider.",["Weather","JobNimbus","Monday","Notes","Stripe","Documents","Stalled files","Executive Intelligence Report"]),
s(4,"Internal TotalScope","Taylor’s Monday morning","Where do I need to focus today?","Live C3 Feature","dashboard","Before the leadership meeting begins, Taylor sees workload, stalled work, aging risk, and storm-driven demand—with every number linked to the people and files behind it.",["New files · 6","Active files · 32","Completed files · 18","Stalled files · 7","Aging files · 12","Weather events · 3","Limited financial data · 2"],"Taylor — Operations"),
s(23,"Internal TotalScope","Recommendations","What action should leadership consider next?","Future Capability","recommendations","Evidence-backed recommendations appear immediately after Taylor’s Monday view and show priority, confidence, estimated impact, supporting facts, and a practical next action.",["High priority · Rebalance 7 aging files · 91% confidence","Growth attention · Contact Harbor Roofing · $48K opportunity","Financial exception · Review 3 failed payments · $4,620 at risk"]),
s(5,"Internal TotalScope","Breson’s financial view","What financial value did we create, and what was collected?","Live C3 Foundation","financial","Approved, traceable outcomes connect settlement value, charges, collections, and exceptions.",["Settlement gain · $12,500","Approved charges · $1,690","Net client gain · $10,046","ROI · 594%","Collected · $1,690","Refunds · $100","Processor fees · $58"],"Breson — Finance and Executive Leadership"),
s(6,"Internal TotalScope","Client health","Which clients are healthy, declining, inactive, or requiring attention?","Vision Preview","client-health","Client health is explained through contributing facts—not hidden behind an unexplained score.",["Submission consistency","Operational friction","Financial value","Branch performance","Data limitations"],"Harbor Roofing — Client Health Review"),
s(7,"Internal TotalScope","Claim-handler performance","Who performs best for specific carriers and operating conditions?","Live C3 Foundation + Vision Preview","handlers","Counts remain visible while comparative conclusions require a qualifying cohort.",["Completed files","Active workload","Average cycle time","Median cycle time","Settlement gain","Minimum comparative cohort · 10"]),
s(8,"Internal TotalScope","Data Health","Can we trust what we are seeing?","Live C3 Feature","data-health","Every result carries coverage, confidence, lineage, and reconciliation context. TSI calls out missing or conflicting facts before leadership relies on them.",["Source health · 5 of 6 current","Records reconciled · 4,281","Financial coverage · 83%","Validation exceptions · 14","Lineage complete · 98%","Sync status · Monday delayed 18m","KPI availability · 97%"]),
s(9,"Internal TotalScope","Summit Roofing Group","What work and value support this client relationship?","Live C3 Foundation","client-detail","A client-level review connects branches, outcomes, carrier mix, and every supporting file.",["Branches · 2","Files · 4","Active / completed · 2 / 2","Settlement gain · $6,500","Approved charges · $1,090","Net gain · $5,410"]),
s(10,"Internal TotalScope","Individual file traceability","What facts support this material result?","Live C3 Foundation","file-detail","Follow one conclusion from file and notes through documents, carrier activity, settlement, invoice, payment, and supporting evidence. No material result is a black box.",["File · TSI-1001","Client · Summit Roofing Group","Carrier · North Star Mutual","Status · Completed","Initial · $10,000","Final · $14,000","Gain · $4,000","Fee · $300"]),
s(11,"Client experience","Client executive overview","What value is TotalScope creating for our company?","Vision Preview","client-portal","Now viewing: Client Portal — Summit Roofing Group",["Files submitted · 38","Active files · 64","Completed this quarter · 91","Settlement gains · $428,600","Fees paid · $31,900","Net client benefit · $396,700","ROI · 1,243%"]),
s(12,"Client experience","Active work","What is progressing, blocked, or waiting on us?","Vision Preview","active-work","A positive, transparent view of current work without emphasizing predicted charges.",["In estimating · 18","Actively handled · 24","Awaiting carrier · 9","Client action required · 4","Nearing completion · 11","Aging files · 7"]),
s(13,"Client experience","Completed outcomes","Which completed files produced measurable value?","Vision Preview","outcomes","Completed outcomes connect carrier movement, paid fees, and client benefit to the underlying file.",["SRG-26041 · $18,400 increase","SRG-26038 · $12,650 increase","SRG-26029 · $9,800 increase"]),
s(14,"Client experience","Trends and benchmarking","How are our branches and carriers changing over time?","Vision Preview","benchmarks","Client-owned trends remain distinct from responsibly anonymized peer benchmarks.",["Monthly submission volume","Average settlement gain","Average turnaround time","Branch comparison","Carrier response patterns","Anonymized peer benchmarks"]),
s(15,"Client experience","Executive Intelligence Report","What should leadership know and do this month?","Vision Preview","report","A polished leadership brief combines financial value, operational attention, trends, and recommended actions—ready to review, download, email, or share.",["Executive summary","Financial value created","Completed outcomes","Files requiring attention","Trends and observations","Recommended actions"]),
s(16,"Client subscriptions","Subscription plans","How could TSI become recurring client value?","Illustrative Business Model","pricing","TSI can become a recurring-revenue product layered on top of TotalScope’s existing services.",["Essential · qualifying volume or $99/mo","Professional · $299/mo","Enterprise · $750–$1,500/mo"]),
s(17,"Client subscriptions","Recurring-revenue example","What could illustrative adoption produce?","Illustrative Business Model","revenue","This scenario demonstrates potential business-model scale and is not a forecast.",["50 Essential × $99 · $4,950/mo","40 Professional × $299 · $11,960/mo","10 Enterprise × $1,000 · $10,000/mo","Illustrative MRR · $26,910","Illustrative ARR · $322,920"]),
s(18,"Client subscriptions","Strategic value beyond subscriptions","How else does client intelligence strengthen TotalScope?","Vision Preview","value","Client intelligence can deepen the relationship while making TotalScope easier to understand and harder to replace.",["Client retention","Submission volume","Sales differentiation","Account reviews","Enterprise acquisition","Renewal conversations","Trust and transparency"]),
s(19,"Industry intelligence","State of the Roofing Industry","What proprietary perspective could governed aggregate data create?","Vision Preview","report-cover","The State of Roofing Claims and Restoration — 2027 Industry Intelligence Report",["Claim-volume trends","Initial and final settlements","Claim uplift","Carrier response times","Disputed categories","Seasonal trends","Operational benchmarks"]),
s(20,"Industry intelligence","External report pricing","Who might buy industry intelligence, and how?","Illustrative Business Model","market-pricing","All external products require approved privacy, aggregation, contractual, and legal policies.",["Digital report · $995","Company license · $2,500","Enterprise license · $10,000+","Regional analysis · $7,500+","Benchmark subscription · $5,000–$25,000"]),
s(21,"Industry intelligence","Additional intelligence products","Which adjacent data products could TSI support?","Vision Preview","products","Responsibly governed, anonymized intelligence can serve a market beyond existing TotalScope clients.",["Regional market reports","Carrier scorecards","Contractor benchmarking","Storm-response intelligence","Industry outlook","Supplier reports","PE due diligence","Custom research"]),
s(22,"Future of TSI","Automated observations","What changed, and why does it matter?","Future Capability","observations","Deterministic observations connect a material change to its contributing metrics, affected clients, trend evidence, and confidence—without pretending to make the decision.",["Submission decline · Three branches explain 71% of the change","Carrier performance · State Farm cohort closed 8 days faster","Payment risk · Failures increased for a second consecutive week"]),
s(24,"Future of TSI","Ask TSI","How can leaders explore governed data conversationally?","Future Capability","ask","Leaders can ask natural-language questions and receive concise answers that retain metric definitions, permissions, confidence, and source traceability.",["What clients have slowed submissions over the last 60 days?","What claim handlers perform best with State Farm?","What files require executive attention today?","What trends should leadership discuss Monday morning?","Where is data unreliable?"]),
s(25,"Future of TSI","The TotalScope Intelligence vision","Where does the platform go from here?","Product Vision","closing","TSI is not simply a dashboard. It becomes the operating intelligence layer that moves TotalScope from governed data to confident strategic decisions.",["Data","Facts","KPIs","Observations","Recommendations","Executive Reports","Ask TSI","Strategic Decisions"])
] as const;
export const PRODUCT_VISION_SECTIONS=[...new Set(PRODUCT_VISION_SCREENS.map(x=>x.section))];
