"use client";
import { useMemo,useState } from "react";
import { useDemoData } from "./data-context";
import type { Claim } from "@/types/intelligence";
const PAGE_SIZE=10;
const labels={captured:"Captured",not_captured:"Not captured",partially_captured:"Partially captured",invalid:"Invalid",not_applicable:"Not applicable"};
export function ClaimsExplorer(){const {claims,data}=useDemoData();const [search,setSearch]=useState("");const [status,setStatus]=useState("");const [financial,setFinancial]=useState("");const [sort,setSort]=useState<keyof Claim>("openedAt");const [direction,setDirection]=useState<"asc"|"desc">("desc");const [page,setPage]=useState(1);const [selected,setSelected]=useState<Claim|null>(null);
 const rows=useMemo(()=>claims.filter(c=>(!search||`${c.claimNumber} ${data.contractors.find(x=>x.id===c.contractorId)?.name} ${data.carriers.find(x=>x.id===c.carrierId)?.name}`.toLowerCase().includes(search.toLowerCase()))&&(!status||c.status===status)&&(!financial||c.financialStatus===financial)).sort((a,b)=>String(a[sort]??"").localeCompare(String(b[sort]??""))*(direction==="asc"?1:-1)),[claims,data,search,status,financial,sort,direction]);
 const pages=Math.max(1,Math.ceil(rows.length/PAGE_SIZE));const visible=rows.slice((Math.min(page,pages)-1)*PAGE_SIZE,Math.min(page,pages)*PAGE_SIZE);
 function sortBy(key:keyof Claim){if(sort===key)setDirection(x=>x==="asc"?"desc":"asc");else{setSort(key);setDirection("asc")}}
 return <><section className="card explorer-controls"><label>Search claims<input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Claim #, contractor, or carrier"/></label><label>File status<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">All statuses</option><option value="new">New</option><option value="estimating">Estimating</option><option value="negotiating">Negotiating</option><option value="stalled">Stalled</option><option value="closed">Closed</option></select></label><label>Financial data<select value={financial} onChange={e=>{setFinancial(e.target.value);setPage(1)}}><option value="">All financial statuses</option>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><span>{rows.length} files</span></section><section className="card claim-table-wrap"><table className="claim-table"><caption className="sr-only">Synthetic restoration claim files matching the selected filters</caption><thead><tr><SortHead label="Claim" col="claimNumber" current={sort} direction={direction} onClick={sortBy}/><SortHead label="Source quarter" col="sourceQuarter" current={sort} direction={direction} onClick={sortBy}/><th>Contractor</th><th>Carrier</th><SortHead label="Opened" col="openedAt" current={sort} direction={direction} onClick={sortBy}/><SortHead label="Status" col="status" current={sort} direction={direction} onClick={sortBy}/><th>Financial data</th><SortHead label="Additional RCV" col="additionalRcv" current={sort} direction={direction} onClick={sortBy}/></tr></thead><tbody>{visible.map(c=><tr key={c.id} tabIndex={0} onClick={()=>setSelected(c)} onKeyDown={e=>{if(e.key==="Enter")setSelected(c)}}><td><b>{c.claimNumber}</b><small>{c.state} {c.zipCode}</small></td><td>{c.sourceQuarter}</td><td>{data.contractors.find(x=>x.id===c.contractorId)?.name}</td><td>{data.carriers.find(x=>x.id===c.carrierId)?.name}</td><td>{c.openedAt}</td><td><span className={`file-status ${c.status}`}>{c.status}</span></td><td><span className={`financial-status ${c.financialStatus}`}>{labels[c.financialStatus]}</span></td><td>{c.additionalRcv===null?"—":c.additionalRcv.toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0})}</td></tr>)}</tbody></table><footer className="pagination"><span>Page {Math.min(page,pages)} of {pages}</span><div><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>Next</button></div></footer></section>{selected&&<ClaimDrawer claim={selected} close={()=>setSelected(null)}/>}</>
}
function SortHead({label,col,current,direction,onClick}:{label:string;col:keyof Claim;current:keyof Claim;direction:"asc"|"desc";onClick:(c:keyof Claim)=>void}){return <th><button onClick={()=>onClick(col)}>{label} {current===col?(direction==="asc"?"↑":"↓"):"↕"}</button></th>}
function ClaimDrawer({claim,close}:{claim:Claim;close:()=>void}){const {data}=useDemoData();return <><button className="drawer-overlay" onClick={close} aria-label="Close claim detail"/><aside className="claim-drawer" role="dialog" aria-modal="true" aria-labelledby="claim-title"><header><div><small>DEMO CLAIM DETAIL</small><h2 id="claim-title">{claim.claimNumber}</h2></div><button onClick={close} aria-label="Close claim detail">×</button></header><div className="drawer-body"><dl><Field l="Source quarter" v={claim.sourceQuarter}/><Field l="Service" v={claim.serviceType.replace("_"," ")}/><Field l="Contractor" v={data.contractors.find(x=>x.id===claim.contractorId)?.name}/><Field l="Carrier" v={data.carriers.find(x=>x.id===claim.carrierId)?.name}/><Field l="Adjuster" v={data.adjusters.find(x=>x.id===claim.adjusterId)?.name}/><Field l="Location" v={`${claim.state} ${claim.zipCode}`}/><Field l="Opened" v={claim.openedAt}/><Field l="Closed" v={claim.closedAt??"Active"}/><Field l="Financial data" v={labels[claim.financialStatus]}/><Field l="Original RCV" v={claim.originalRcv===null?"Unavailable":`$${claim.originalRcv.toLocaleString()}`}/><Field l="Additional RCV" v={claim.additionalRcv===null?"Unavailable":`$${claim.additionalRcv.toLocaleString()}`}/><Field l="TotalScope fee" v={claim.totalScopeFee===null?"Unavailable":`$${claim.totalScopeFee.toLocaleString()}`}/></dl><h3>Updates & notes</h3><ol>{claim.updates.map((u,i)=><li key={i}><i/><div><b>{u.summary}</b><span>{u.at} · {u.author} · {u.type}</span></div></li>)}</ol></div></aside></>}
function Field({l,v}:{l:string;v:string|undefined}){return <div><dt>{l}</dt><dd>{v}</dd></div>}
