"use client";
import { useDemoData } from "./data-context";
import { activeInventory, additionalRcv, averageAdditionalRcv, averageCycleTime, feeRevenue, financialCoverage, totalFiles } from "@/lib/calculations";
import { buildObservations } from "@/lib/observations";
import { filterClaims } from "@/lib/filters";
import { DataKpi } from "@/components/ui/data-kpi";
import { SectionCard } from "@/components/ui/section-card";
import { ObservationList } from "./observation-list";
const money=(v:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",notation:"compact",maximumFractionDigits:1}).format(v);
export function ExecutiveDashboard(){const {claims,data,filters}=useDemoData();const qIndex=data.quarters.indexOf(filters.quarter);const prior=filterClaims(data.claims,{...filters,quarter:qIndex>0?data.quarters[qIndex-1]:""});const observations=buildObservations(claims,prior,data.carriers,data.weatherEvents,data.claimWeatherMatches);const quarterCounts=data.quarters.map(q=>({q,count:filterClaims(data.claims,{...filters,quarter:q}).length}));return <><div className="data-kpi-grid"><DataKpi label="Total submitted files" result={totalFiles(claims)}/><DataKpi label="Active claim inventory" result={activeInventory(claims)} tone="amber"/><DataKpi label="Additional RCV" result={additionalRcv(claims)} format={money} tone="green"/><DataKpi label="TotalScope fee revenue" result={feeRevenue(claims)} format={money}/><DataKpi label="Average additional RCV" result={averageAdditionalRcv(claims)} format={money}/><DataKpi label="Average cycle time" result={averageCycleTime(claims)} format={v=>`${v.toFixed(1)} days`}/><DataKpi label="Financial coverage" result={financialCoverage(claims)} format={v=>`${v.toFixed(1)}%`} tone="amber"/></div><div className="content-grid executive-grid"><SectionCard eyebrow="NINE-QUARTER TREND" title="Submitted file volume"><div className="bar-chart" role="img" aria-label="Submitted file volume by source quarter">{quarterCounts.map(x=><div key={x.q}><span style={{height:`${Math.max(8,x.count/Math.max(...quarterCounts.map(y=>y.count))*100)}%`}}/><small>{x.q.replace("20","’")}</small><b>{x.count}</b></div>)}</div></SectionCard><SectionCard eyebrow="DETERMINISTIC ANALYSIS" title="Intelligence observations"><ObservationList items={observations}/></SectionCard></div></>}
