"use client";
import Link from "next/link";
import { useMemo,useState } from "react";
import type { LiveClaimListItem } from "@/types/live-intelligence";
const PAGE_SIZE=20;
export function LiveClaimsExplorer({claims}:{claims:LiveClaimListItem[]}){const [search,setSearch]=useState("");const [status,setStatus]=useState("");const [contractor,setContractor]=useState("");const [carrier,setCarrier]=useState("");const [sort,setSort]=useState<"mondayItemId"|"displayName"|"rawStatus">("mondayItemId");const [desc,setDesc]=useState(false);const [page,setPage]=useState(1);
  const contractors=[...new Set(claims.map(c=>c.contractor).filter(Boolean))] as string[];const carriers=[...new Set(claims.map(c=>c.carrier).filter(Boolean))] as string[];
  const rows=useMemo(()=>claims.filter(c=>(!search||`${c.displayName} ${c.mondayItemId}`.toLowerCase().includes(search.toLowerCase()))&&(!status||c.rawStatus===status)&&(!contractor||c.contractor===contractor)&&(!carrier||c.carrier===carrier)).sort((a,b)=>String(a[sort]??"").localeCompare(String(b[sort]??""))*(desc?-1:1)),[claims,search,status,contractor,carrier,sort,desc]);
  const pages=Math.max(1,Math.ceil(rows.length/PAGE_SIZE));const current=Math.min(page,pages);const visible=rows.slice((current-1)*PAGE_SIZE,current*PAGE_SIZE);
  function sortBy(key:typeof sort){if(sort===key)setDesc(x=>!x);else{setSort(key);setDesc(false)}}
  return <><section className="card explorer-controls"><label>Search<input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Claim name or Monday Item ID"/></label><label>Status<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">All</option><option>Complete</option><option>Closed</option></select></label><label>Contractor<select value={contractor} onChange={e=>{setContractor(e.target.value);setPage(1)}}><option value="">All</option>{contractors.sort().map(v=><option key={v}>{v}</option>)}</select></label><label>Carrier<select value={carrier} onChange={e=>{setCarrier(e.target.value);setPage(1)}}><option value="">All</option>{carriers.sort().map(v=><option key={v}>{v}</option>)}</select></label><span>{rows.length} claims</span></section><section className="card claim-table-wrap"><table className="claim-table"><caption className="sr-only">Q2 2026 live Monday archive claims</caption><thead><tr><th><button onClick={()=>sortBy("mondayItemId")}>Monday Item ID</button></th><th><button onClick={()=>sortBy("displayName")}>Claim</button></th><th><button onClick={()=>sortBy("rawStatus")}>Status</button></th><th>Contractor</th><th>Carrier</th><th>Source row</th></tr></thead><tbody>{visible.map(c=><tr key={c.id}><td><Link href={`/claims/${c.id}`}>{c.mondayItemId}</Link></td><td>{c.displayName??"Unnamed source claim"}</td><td><span className="financial-status captured">{c.rawStatus??"Unavailable"}</span></td><td>{c.contractor??"Unresolved"}</td><td>{c.carrier??"Unresolved"}</td><td>{c.sourceRow}</td></tr>)}</tbody></table><footer className="pagination"><span>Page {current} of {pages}</span><div><button disabled={current<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><button disabled={current>=pages} onClick={()=>setPage(p=>p+1)}>Next</button></div></footer></section></>}
