"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { WeatherIntelligenceMap } from "@/components/dashboard/weather-intelligence-map";
import type { AggregatedWeatherOpportunity, ClientExposure, OpportunityLevel, WeatherIntelligenceSnapshot } from "@/lib/weather/contracts";
import { aggregateWeatherOpportunities } from "@/lib/weather/opportunity-aggregation";
import { formatAffectedGeography } from "@/lib/weather/affected-geography";
import { deriveForecastSignals } from "@/lib/weather/forecast-signals";

const WINDOWS = [24, 48, 72, 168] as const;
const LEVEL_RANK: Record<OpportunityLevel, number> = { active: 3, high: 2, elevated: 1, monitor: 0 };
const date = (value: string | null) => value ? new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Unavailable";
const shortDate = (value: string) => new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", hour: "numeric" }).format(new Date(value));
const relatedExposures = (opportunity: AggregatedWeatherOpportunity, exposures: ClientExposure[]) => exposures.filter((exposure) => opportunity.sourceAlertIds.includes(exposure.weatherOpportunityId));
const matchesOpportunityBand = (score: number, band: "high" | "moderate" | "low" | null) => band === null || band === "high" ? band === null || score >= 70 : band === "moderate" ? score >= 45 && score < 70 : score < 45;

export function LiveWeatherDashboard({ snapshot }: { snapshot: WeatherIntelligenceSnapshot }) {
  const [hours, setHours] = useState<(typeof WINDOWS)[number]>(24);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [sort, setSort] = useState("opportunity");
  const [eventFilter, setEventFilter] = useState("all");
  const [geographyFilter, setGeographyFilter] = useState("all");
  const [exposureFilter, setExposureFilter] = useState("all");
  const [showAllZctas, setShowAllZctas] = useState(false);
  const [opportunityBand, setOpportunityBand] = useState<"high" | "moderate" | "low" | null>(null);
  const activeAlertCatalogRef = useRef<HTMLDetailsElement>(null);
  const opportunities = useMemo(() => aggregateWeatherOpportunities(snapshot.alerts, snapshot.generatedAt, hours), [hours, snapshot.alerts, snapshot.generatedAt]);
  const eventFamilies = useMemo(() => [...new Set(opportunities.map((item) => item.normalizedEventType))].sort(), [opportunities]);
  const geographies = useMemo(() => [...new Set(opportunities.flatMap((item) => item.affectedGeography))].sort(), [opportunities]);
  const visible = useMemo(() => opportunities
    .filter((item) => matchesOpportunityBand(item.weatherOpportunity.score, opportunityBand))
    .filter((item) => eventFilter === "all" || item.normalizedEventType === eventFilter)
    .filter((item) => geographyFilter === "all" || item.affectedGeography.includes(geographyFilter))
    .filter((item) => exposureFilter === "all" || relatedExposures(item, snapshot.clientExposures).some((exposure) => exposure.status !== "unknown"))
    .sort((left, right) => sort === "time" ? left.startsAt.localeCompare(right.startsAt)
      : sort === "geography" ? left.title.localeCompare(right.title)
        : sort === "severity" ? right.weatherSeverity.score - left.weatherSeverity.score || left.startsAt.localeCompare(right.startsAt)
          : right.weatherOpportunity.score - left.weatherOpportunity.score || LEVEL_RANK[right.level] - LEVEL_RANK[left.level] || left.startsAt.localeCompare(right.startsAt)),
  [eventFilter, exposureFilter, geographyFilter, opportunities, opportunityBand, snapshot.clientExposures, sort]);
  const selected = visible.find((item) => item.id === selectedId) ?? visible[0] ?? null;
  const forecastSignals = useMemo(() => deriveForecastSignals(snapshot.forecasts, snapshot.generatedAt, hours), [hours, snapshot.forecasts, snapshot.generatedAt]);
  const mapScopeKey = `${hours}:${opportunityBand ?? "all"}:${eventFilter}:${geographyFilter}:${exposureFilter}`;

  useEffect(() => { if (selected && selected.id !== selectedId) setSelectedId(selected.id); }, [selected, selectedId]);

  const highPriority = opportunities.filter((item) => item.weatherOpportunity.score >= 70).length;
  const elevated = opportunities.filter((item) => item.weatherOpportunity.score >= 45 && item.weatherOpportunity.score < 70).length;
  const monitor = opportunities.filter((item) => item.weatherOpportunity.score < 45).length;

  return <div className="weather-command-center">
    <section className="weather-command-summary" aria-label="Weather operational summary">
      {([['high', 'HIGH OPPORTUNITY', highPriority, 'Investigate first'], ['moderate', 'MODERATE', elevated, 'Review conditions'], ['low', 'LOW', monitor, 'Maintain awareness']] as const).map(([band, label, count, description]) => <button key={band} type="button" aria-pressed={opportunityBand === band} className={opportunityBand === band ? "active" : ""} onClick={() => setOpportunityBand((current) => current === band ? null : band)}><small>{label}</small><strong>{count}</strong><span>{description}</span></button>)}<button type="button" onClick={() => { if (activeAlertCatalogRef.current) { activeAlertCatalogRef.current.open = true; activeAlertCatalogRef.current.scrollIntoView({ behavior: "smooth" }); } }}><small>ACTIVE ALERTS</small><strong>{snapshot.alerts.length}</strong><span>Open official source records</span></button><div className="weather-provider-compact"><small>LAST WEATHER UPDATE</small><strong>{date(snapshot.providerStatus.lastSuccessfulRefresh)}</strong><span className={`provider-state ${snapshot.providerStatus.state}`}>{snapshot.providerStatus.state.replace("_", " ")}</span></div>
    </section>
    {snapshot.errors.length > 0 && <section className="weather-errors" role="status"><strong>Some Weather Intelligence services are unavailable</strong><ul>{snapshot.errors.map((error) => <li key={error}>{error}</li>)}</ul></section>}

    <section className="weather-workspace">
      <header className="weather-workspace-header"><div><small>OPERATIONAL WEATHER PICTURE</small><h2>Where should TotalScope focus?</h2><p>Official alerts are grouped and ranked by deterministic restoration-business relevance.</p></div><div className="forecast-window" aria-label="Weather time horizon">{WINDOWS.map((window) => <button type="button" className={hours === window ? "active" : ""} key={window} onClick={() => setHours(window)}>{window === 168 ? "7 days" : `${window} hours`}</button>)}</div></header>
      <div className="weather-map-layout"><WeatherIntelligenceMap opportunities={visible} selectedId={selected?.id ?? null} monitoredLocations={snapshot.monitoredLocations} forecasts={snapshot.forecasts} forecastSignals={forecastSignals} clientExposures={snapshot.clientExposures} scopeKey={mapScopeKey} onSelect={setSelectedId} />
        <aside className="weather-priority-panel"><div className="weather-list-heading"><div><small>PRIORITIZED OPPORTUNITIES</small><strong>{visible.length} operational groups</strong></div><span>{snapshot.alerts.length} alerts analyzed</span></div>
          <div className="weather-list-filters"><label>Sort<select value={sort} onChange={(event) => setSort(event.target.value)}><option value="opportunity">Weather Opportunity</option><option value="severity">Weather Severity</option><option value="time">Timing</option><option value="geography">Geography</option></select></label><label>Event<select value={eventFilter} onChange={(event) => setEventFilter(event.target.value)}><option value="all">All types</option>{eventFamilies.map((family) => <option key={family}>{family}</option>)}</select></label><label>Geography<select value={geographyFilter} onChange={(event) => setGeographyFilter(event.target.value)}><option value="all">All areas</option>{geographies.map((area) => <option key={area}>{area}</option>)}</select></label><label>Clients<select value={exposureFilter} onChange={(event) => setExposureFilter(event.target.value)}><option value="all">All exposure</option><option value="known">Known exposure</option></select></label></div>
          <div className="weather-opportunity-list">{visible.map((opportunity) => <button key={opportunity.id} type="button" className={selected?.id === opportunity.id ? "selected" : ""} onClick={() => { setSelectedId(opportunity.id); setShowAllZctas(false); }}><span className={`opportunity-level ${opportunity.level}`}>{opportunity.weatherOpportunity.label} opportunity · {opportunity.weatherOpportunity.score}</span><h3>{opportunity.title}</h3><p>{opportunity.normalizedEventType} · {shortDate(opportunity.startsAt)}–{shortDate(opportunity.endsAt)}</p><dl><div><dt>Weather severity</dt><dd>{opportunity.weatherSeverity.label} · {opportunity.weatherSeverity.score}</dd></div><div><dt>Source alerts</dt><dd>{opportunity.sourceAlerts.length}</dd></div><div><dt>Known clients</dt><dd>Awaiting import</dd></div></dl></button>)}{!visible.length && <div className="weather-empty"><strong>No opportunities match these controls</strong><p>Adjust the filters or time horizon. No synthetic event has been substituted.</p></div>}</div>
        </aside>
      </div>
    </section>

    <section className="weather-selected-detail" aria-live="polite">{selected ? <><header><div><small>SELECTED OPPORTUNITY</small><h2>{selected.title}</h2><p>{selected.normalizedEventType} · {selected.weatherOpportunity.label} Weather Opportunity · {selected.sourceAlerts.length} official source {selected.sourceAlerts.length === 1 ? "alert" : "alerts"}</p></div><span>Fresh as of {date(snapshot.generatedAt)}</span></header><div className="weather-detail-grid">
      <article><small>WEATHER SUMMARY</small><dl><div><dt>Normalized event type</dt><dd>{selected.normalizedEventType}</dd></div><div><dt>Weather Opportunity</dt><dd>{selected.weatherOpportunity.label} · {selected.weatherOpportunity.score}/100 <span title={`Scoring model ${selected.weatherOpportunity.modelVersion}`}>ⓘ</span></dd></div><div><dt>Weather Severity</dt><dd>{selected.weatherSeverity.label} · {selected.weatherSeverity.score}/100 (NWS: {selected.weatherSeverity.sourceSeverity || "unavailable"})</dd></div><div><dt>Timing</dt><dd>{date(selected.startsAt)} to {date(selected.endsAt)}</dd></div><div><dt>Supported hail indicator</dt><dd>{selected.weatherOpportunity.evidence.hailSupported ? selected.weatherOpportunity.evidence.hailSizeInches == null ? "Hail explicitly present; size not supplied" : `Hail up to ${selected.weatherOpportunity.evidence.hailSizeInches} in` : "Not supported by official source"}</dd></div><div><dt>Supported wind indicator</dt><dd>{selected.weatherOpportunity.evidence.damagingWindSupported ? selected.weatherOpportunity.evidence.maximumWindMph == null ? "Damaging/high wind explicitly present; value not supplied" : `Wind up to ${selected.weatherOpportunity.evidence.maximumWindMph} mph` : "Not supported by official source"}</dd></div><div><dt>Affected geography</dt><dd>{formatAffectedGeography(selected.affectedGeography).join("; ") || "Not supplied by provider"}</dd></div><div><dt>Affected ZIP Codes</dt><dd>{selected.zctaStatus === "available" ? selected.affectedZctas.length ? <>{(showAllZctas ? selected.affectedZctas : selected.affectedZctas.slice(0, 5)).join(", ")}{!showAllZctas && selected.affectedZctas.length > 5 ? ` +${selected.affectedZctas.length - 5} more` : ""}{selected.affectedZctas.length > 5 && <button type="button" className="weather-zcta-toggle" onClick={() => setShowAllZctas((value) => !value)}>{showAllZctas ? "Collapse" : "Show all"}</button>}<small>Approximate affected ZIP areas based on U.S. Census ZIP Code Tabulation Areas (ZCTAs).</small></> : "Unable to determine affected ZIP areas from available storm geometry." : selected.zctaMethodology}</dd></div><div><dt>Data freshness</dt><dd>{date(snapshot.generatedAt)}</dd></div></dl><details className="weather-score-breakdown"><summary>Why this opportunity ranks here</summary><ol>{selected.weatherOpportunity.breakdown.map((component) => <li key={component.key}><span>{component.label}</span><strong>+{component.points}</strong></li>)}</ol><small>{selected.weatherOpportunity.modelVersion}</small></details><p className="weather-caution">An official alert indicates a review opportunity; it does not establish property damage.</p></article>
      <article><small>EXISTING TOTALSCOPE CLIENTS</small>{relatedExposures(selected, snapshot.clientExposures).filter((exposure) => exposure.status !== "outside").length ? <div className="weather-client-exposures">{relatedExposures(selected, snapshot.clientExposures).filter((exposure) => exposure.status !== "outside").map((exposure) => <div key={`${exposure.weatherOpportunityId}:${exposure.branchId}`}><strong>{exposure.clientName}</strong><span>{[exposure.branchName, exposure.city, exposure.state, exposure.postalCode].filter(Boolean).join(", ")}</span><dl><div><dt>Relationship</dt><dd>{exposure.status}</dd></div><div><dt>Distance</dt><dd>{exposure.distanceKm == null ? "Unavailable" : `${exposure.distanceKm.toFixed(1)} km`}</dd></div><div><dt>Precision</dt><dd>{exposure.locationPrecision.replaceAll("_", " ")}</dd></div></dl><a href={`/operations/clients/${exposure.clientId}`}>View in TSI</a></div>)}</div> : <div className="weather-detail-empty"><strong>Current-client geography unavailable</strong><p>No governed, current, high-precision client location can be evaluated for this opportunity. No client location or coordinate is fabricated.</p></div>}</article>
      <article><small>POTENTIAL CONTRACTORS · 50 KM</small><div className="weather-detail-empty"><strong>Contractor discovery provider not yet configured.</strong><p>{snapshot.contractorProviderStatus.message} No fictional contractor results are shown.</p></div></article>
    </div><details className="weather-source-alerts"><summary>Source alerts and official provenance <span>{selected.sourceAlerts.length}</span></summary><div>{selected.sourceAlerts.map((alert) => <article key={alert.sourceId}><div><strong>{alert.event}</strong><span>{alert.areaDescription || "Area unavailable"}</span></div><dl><div><dt>Official product</dt><dd>{alert.event}</dd></div><div><dt>Severity</dt><dd>{alert.severity || "Unavailable"}</dd></div><div><dt>Certainty</dt><dd>{alert.certainty || "Unavailable"}</dd></div><div><dt>Retrieved</dt><dd>{date(alert.retrievedAt)}</dd></div></dl><a href={alert.sourceUrl} target="_blank" rel="noreferrer">Official NWS source ↗</a></article>)}</div></details></> : <div className="weather-empty"><strong>No active operational opportunity</strong><p>The official provider returned no material alert group for this horizon.</p></div>}</section>

    <section className="weather-forecast-summary"><header><div><small>FORECAST-DERIVED · NOT ISSUED ALERTS</small><h2>Upcoming Weather to Watch</h2></div><span>{snapshot.monitoredLocations.length} monitored forecast locations · {hours === 168 ? "7 days" : `${hours} hours`}</span></header>{forecastSignals.length ? <div className="forecast-grid">{forecastSignals.slice(0, 12).map((signal) => <article key={signal.id}><small>{signal.locationName} · {signal.period.name}</small><h3>{signal.eventType}</h3><p>{signal.period.shortForecast} · Wind {signal.period.windSpeed ?? "unavailable"} {signal.period.windDirection ?? ""}</p><span>{signal.rationale}</span></article>)}</div> : <div className="weather-empty"><strong>No significant upcoming restoration-relevant weather identified in the current forecast context.</strong><p>Ordinary sunny, clear, and otherwise benign periods are intentionally suppressed.</p></div>}</section>
    <details ref={activeAlertCatalogRef} className="weather-admin-diagnostics"><summary>Provider diagnostics and complete active-alert catalog</summary><div><section><small>PROVIDER HEALTH</small><dl><div><dt>Provider</dt><dd>{snapshot.providerStatus.provider.toUpperCase()}</dd></div><div><dt>Status</dt><dd>{snapshot.providerStatus.state.replace("_", " ")}</dd></div><div><dt>Last attempt</dt><dd>{date(snapshot.providerStatus.lastAttemptedRefresh)}</dd></div><div><dt>Last success</dt><dd>{date(snapshot.providerStatus.lastSuccessfulRefresh)}</dd></div></dl><p>{snapshot.providerStatus.message}</p></section><section><small>ACTIVE / ISSUED WEATHER ALERTS</small><p>{snapshot.alerts.length} official alerts are retained as supporting evidence. These source records are distinct from aggregated Weather Opportunities and forecast-derived weather to watch.</p></section></div></details>
  </div>;
}
