import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { PRODUCT_VISION_SCREENS } from "../config/product-vision/screens.ts";

const component = readFileSync("components/product-vision/product-vision-demo.tsx","utf8");
const shell = readFileSync("components/dashboard/shell.tsx","utf8");

test("Product Vision Demo contains the approved 25-screen narrative",()=>{
  assert.equal(PRODUCT_VISION_SCREENS.length,25);
  assert.deepEqual(PRODUCT_VISION_SCREENS.map(screen=>screen.id).toSorted((a,b)=>a-b),Array.from({length:25},(_,index)=>index+1));
  assert.equal(new Set(PRODUCT_VISION_SCREENS.map(screen=>screen.section)).size,6);
});
test("recommendations follow Taylor's Monday morning",()=>{
  const taylor=PRODUCT_VISION_SCREENS.findIndex(screen=>screen.title==="Taylor’s Monday morning");
  const recommendations=PRODUCT_VISION_SCREENS.findIndex(screen=>screen.title==="Recommendations");
  assert.equal(recommendations,taylor+1);
});
test("every screen declares status, question, purpose, and synthetic highlights",()=>{
  for(const screen of PRODUCT_VISION_SCREENS){
    assert.ok(screen.status);
    assert.ok(screen.question.endsWith("?"));
    assert.ok(screen.message.length>20);
    assert.ok(screen.highlights.length>=3);
  }
});
test("navigation supports controls, keyboard, counter, section index, and exit",()=>{
  assert.match(component,/ArrowRight/);
  assert.match(component,/ArrowLeft/);
  assert.match(component,/Escape/);
  assert.match(component,/Previous/);
  assert.match(component,/Next →/);
  assert.match(component,/index \+ 1} of 25/);
  assert.match(component,/Demo sections/);
  assert.match(component,/Exit Product Vision Demo/);
  assert.match(component,/MetricDetail/);
  assert.match(component,/data-tip/);
});
test("authenticated shell exposes the Product Vision Demo launcher",()=>{
  assert.match(shell,/Product Vision Demo/);
  assert.match(shell,/setVisionOpen\(true\)/);
  assert.match(shell,/ProductVisionDemo open=\{visionOpen\}/);
});
test("demo remains presentation-only and does not access data or mutation clients",()=>{
  for(const source of [component,readFileSync("config/product-vision/screens.ts","utf8")]){
    assert.doesNotMatch(source,/createClient|supabase|service_role|insert\(|update\(|delete\(|fetch\(/i);
  }
});
test("executive redesign includes drill-down evidence and outcome-led visuals",()=>{
  assert.match(component,/Supporting examples/);
  assert.match(component,/Why leadership should care/);
  assert.match(component,/ExecutiveReport/);
  assert.match(component,/FileTrace/);
  assert.match(component,/OutcomePipeline/);
  assert.match(component,/StormMap/);
  assert.match(component,/Kansas City hail/);
  assert.match(component,/detailData/);
  assert.match(component,/ContractorRadiusModal/);
  assert.match(component,/KANSAS_CITY_ROOFERS/);
  assert.match(component,/Current client/);
  assert.match(component,/Not a client/);
  assert.match(component,/View TS profile/);
  assert.match(component,/Visit website/);
  assert.match(component,/company\.client \?/);
  assert.match(component,/StormEvidence/);
  assert.match(component,/Expected inspection demand/);
  assert.match(component,/Conceptual data sources/);
  assert.match(component,/Demo values are fabricated/);
  assert.match(component,/FileStatsModal/);
  assert.match(component,/OperationalFileSummary/);
  assert.match(component,/WHY THIS FILE IS STALLED/);
  assert.match(component,/No activity note for 12 days/);
  assert.match(component,/Carrier desk adjuster has not responded/);
  assert.match(component,/RecommendationEvidence/);
  assert.match(component,/WHY TSI GENERATED THIS/);
  assert.match(component,/Estimated impact/);
  assert.match(component,/Recommended action plan/);
  assert.match(component,/PAY-88421/);
  assert.match(component,/SupportingRecordModal/);
  assert.match(component,/supportingRecordDetail/);
  assert.match(component,/Open supporting information/);
  assert.match(component,/APPROPRIATE NEXT ACTION/);
  assert.match(component,/FinancialEvidence/);
  assert.match(component,/Settlement value bridge/);
  assert.match(component,/Client net-gain reconciliation/);
  assert.match(component,/Processor-fee reconciliation/);
  assert.match(component,/ClientHealthEvidence/);
  assert.match(component,/Submission cadence and consistency/);
  assert.match(component,/Operational-friction breakdown/);
  assert.match(component,/Data limitations and confidence/);
  assert.match(component,/Client Health · Harbor Roofing/);
  assert.match(component,/HandlerEvidence/);
  assert.match(component,/Completed-file qualification/);
  assert.match(component,/Current workload and capacity/);
  assert.match(component,/Comparative-cohort rule/);
  assert.match(component,/DataHealthEvidence/);
  assert.match(component,/Source freshness and availability/);
  assert.match(component,/Record reconciliation control/);
  assert.match(component,/KPI availability and blockers/);
  assert.match(component,/ClientDetailEvidence/);
  assert.match(component,/Summit branch operating profile/);
  assert.match(component,/Summit approved-charge ledger/);
  assert.match(component,/Summit net-client-gain bridge/);
  assert.match(component,/ClientPortalEvidence/);
  assert.match(component,/WHAT THIS MEANS FOR SUMMIT/);
  assert.match(component,/YOUR SUBMISSION STORY/);
  assert.match(component,/RETURN ON INVESTMENT/);
  assert.match(component,/ActiveWorkEvidence/);
  assert.match(component,/CompletedOutcomeEvidence/);
  assert.match(component,/BenchmarkEvidence/);
  assert.match(component,/WHAT YOU SHOULD KNOW/);
  assert.match(component,/Completed PROJECT|COMPLETED PROJECT/);
  assert.match(component,/Anonymized peer benchmark/);
  assert.match(component,/PricingTierEvidence/);
  assert.match(component,/TSI Essential/);
  assert.match(component,/TSI Professional/);
  assert.match(component,/TSI Enterprise/);
  assert.match(component,/Example onboarding journey/);
  assert.match(component,/Recurring revenue calculator/);
  assert.match(component,/Subscription assumptions/);
  assert.match(component,/type="range"/);
  assert.match(component,/Monthly recurring revenue/);
  assert.match(component,/Annual recurring revenue/);
  assert.match(component,/StrategicValueEvidence/);
  assert.match(component,/STRATEGIC VALUE PATH/);
  assert.match(component,/How TSI creates this value/);
  assert.match(component,/GOVERNANCE BOUNDARY/);
  assert.match(component,/Storm History Impact/);
  assert.match(component,/IndustryReportEvidence/);
  assert.match(component,/HISTORICAL INDUSTRY ANALYSIS/);
  assert.match(component,/does not predict when or where a future storm will occur/);
  assert.doesNotMatch(component,/Regional storm outlook/i);
  assert.match(component,/MarketPricingEvidence/);
  assert.match(component,/REQUIRED BEFORE SALE/);
  assert.match(component,/IntelligenceProductEvidence/);
  assert.match(component,/CONCEPTUAL INTELLIGENCE PRODUCT/);
  assert.match(component,/ObservationEvidence/);
  assert.match(component,/DETERMINISTIC OBSERVATION/);
  assert.match(component,/What contributed/);
});
