import Link from "next/link";
import { Brand } from "@/components/brand";
import { MiniChart } from "@/components/ui/mini-chart";

export default function Home() {
  return <main className="landing">
    <nav className="landing-nav"><Brand/><div className="landing-links"><a href="#platform">Platform</a><a href="#intelligence">Intelligence</a><a href="#security">Security</a></div><div className="nav-actions"><Link className="button ghost" href="/login">Sign in</Link><Link className="button" href="/dashboard">Explore platform <span>↗</span></Link></div></nav>
    <section className="hero"><div className="eyebrow"><span className="live-dot"/> Intelligence infrastructure for restoration operations</div><h1>Turn every file into<br/><em>operational clarity.</em></h1><p>TotalScope connects estimating, claim handling, carrier response, contractor performance, and financial outcomes in one executive operating view.</p><div className="hero-actions"><Link className="button large" href="/dashboard">Explore the Demo Data <span>↗</span></Link><a className="text-link" href="#platform">Discover the platform <span>↓</span></a></div><div className="proof-row"><span>Built for restoration intelligence</span><span>•</span><span>Transparent financial coverage</span><span>•</span><span>Decision-ready operations</span></div></section>
    <section className="product-frame" id="platform"><div className="frame-top"><Brand compact/><span>Demo executive overview</span><div><i/><i/><i/></div></div><div className="frame-body"><div className="preview-side"><span className="active">Executive</span><span>Claims</span><span>Operations</span><span>Carriers</span><span>Contractors</span></div><div className="preview-main"><div className="preview-heading"><div><small>RESTORATION PERFORMANCE · DEMO DATA</small><h3>Executive intelligence</h3></div><span>Nine quarters⌄</span></div><div className="preview-kpis"><PreviewKpi label="Submitted files" value="126" delta="Synthetic"/><PreviewKpi label="Active inventory" value="68" delta="Demo Data"/><PreviewKpi label="Additional RCV" value="$1.2M" delta="Coverage shown"/><PreviewKpi label="Cycle time" value="42.8 d" delta="Measured" alert/></div><div className="preview-grid"><div className="preview-panel chart-panel"><div><small>OPERATIONAL THROUGHPUT</small><b>126 files</b><span>Nine-quarter synthetic view</span></div><MiniChart values={[22,31,26,45,39,54,48,66,61,74,70,88]}/></div><div className="preview-panel"><small>INTELLIGENCE OBSERVATIONS</small><Signal color="amber" title="File aging risk" text="Deterministic threshold"/><Signal color="cyan" title="Carrier concentration" text="File-mix analysis"/><Signal color="green" title="Financial coverage" text="Missing data stays missing"/></div></div></div></div></section>
    <section className="landing-stats" id="intelligence"><div><strong>9</strong><span>demo quarters</span></div><div><strong>5</strong><span>financial statuses</span></div><div><strong>360°</strong><span>claim operations view</span></div><div><strong>100%</strong><span>synthetic demonstration</span></div></section>
    <footer className="landing-footer"><Brand/><p>Clarity across every property decision.</p><span>© 2026 TotalScope Intelligence</span></footer>
  </main>;
}
function PreviewKpi({label,value,delta,alert}:{label:string;value:string;delta:string;alert?:boolean}) { return <div className="preview-kpi"><small>{label}</small><b>{value}</b><span className={alert?"alert":""}>{delta}</span></div> }
function Signal({color,title,text}:{color:string;title:string;text:string}) { return <div className="preview-signal"><i className={color}/><div><b>{title}</b><span>{text}</span></div><em>›</em></div> }
