import Link from "next/link";
import { Brand } from "@/components/brand";
import { MiniChart } from "@/components/ui/mini-chart";

export default function Home() {
  return <main className="landing">
    <nav className="landing-nav"><Brand/><div className="landing-links"><a href="#platform">Platform</a><a href="#intelligence">Intelligence</a><a href="#security">Security</a></div><div className="nav-actions"><Link className="button ghost" href="/login">Sign in</Link><Link className="button" href="/dashboard">Explore platform <span>↗</span></Link></div></nav>
    <section className="hero"><div className="eyebrow"><span className="live-dot"/> Intelligence infrastructure for property insurance</div><h1>See the entire risk.<br/><em>Act with precision.</em></h1><p>TotalScope unifies weather, carrier, contractor, and portfolio intelligence into one executive operating view—so every decision starts with context.</p><div className="hero-actions"><Link className="button large" href="/dashboard">View executive dashboard <span>↗</span></Link><a className="text-link" href="#platform">Discover the platform <span>↓</span></a></div><div className="proof-row"><span>Built for complex property portfolios</span><span>•</span><span>Live exposure intelligence</span><span>•</span><span>Decision-ready reporting</span></div></section>
    <section className="product-frame" id="platform"><div className="frame-top"><Brand compact/><span>Executive overview</span><div><i/><i/><i/></div></div><div className="frame-body"><div className="preview-side"><span className="active">Overview</span><span>Weather</span><span>Carriers</span><span>Contractors</span><span>Reports</span></div><div className="preview-main"><div className="preview-heading"><div><small>PORTFOLIO COMMAND CENTER</small><h3>Good morning, Olivia.</h3></div><span>Last 30 days⌄</span></div><div className="preview-kpis"><PreviewKpi label="Total exposure" value="$482.6M" delta="+8.4%"/><PreviewKpi label="Active properties" value="1,284" delta="+24"/><PreviewKpi label="At-risk assets" value="38" delta="-12%" alert/><PreviewKpi label="Open claims" value="126" delta="$8.2M"/></div><div className="preview-grid"><div className="preview-panel chart-panel"><div><small>PORTFOLIO EXPOSURE</small><b>$482.6M</b><span>▲ 8.4% vs prior period</span></div><MiniChart values={[22,31,26,45,39,54,48,66,61,74,70,88]}/></div><div className="preview-panel"><small>INTELLIGENCE PULSE</small><Signal color="amber" title="Severe weather watch" text="14 assets · Central Plains"/><Signal color="cyan" title="Carrier capacity shift" text="3 markets updated appetite"/><Signal color="green" title="Contractor coverage" text="96.8% network availability"/></div></div></div></div></section>
    <section className="landing-stats" id="intelligence"><div><strong>4.2×</strong><span>faster risk triage</span></div><div><strong>96.8%</strong><span>network coverage</span></div><div><strong>12 min</strong><span>average signal latency</span></div><div><strong>360°</strong><span>portfolio visibility</span></div></section>
    <footer className="landing-footer"><Brand/><p>Clarity across every property decision.</p><span>© 2026 TotalScope Intelligence</span></footer>
  </main>;
}
function PreviewKpi({label,value,delta,alert}:{label:string;value:string;delta:string;alert?:boolean}) { return <div className="preview-kpi"><small>{label}</small><b>{value}</b><span className={alert?"alert":""}>{delta}</span></div> }
function Signal({color,title,text}:{color:string;title:string;text:string}) { return <div className="preview-signal"><i className={color}/><div><b>{title}</b><span>{text}</span></div><em>›</em></div> }
