import { agingBuckets, averageAdditionalRcv, averageCycleTime, carrierMix, daysSinceLastUpdate, financialCoverage } from "./calculations";
import type { Carrier, Claim, ClaimWeatherMatch, Observation, WeatherEvent } from "@/types/intelligence";

export function buildObservations(current:Claim[],prior:Claim[],carriers:Carrier[],weather:WeatherEvent[],matches:ClaimWeatherMatch[]):Observation[]{
 const out:Observation[]=[]; const pct=(a:number,b:number)=>b?((a-b)/b)*100:0;
 const volumeChange=pct(current.length,prior.length); out.push({id:"volume",severity:volumeChange>=0?"info":"warning",title:`Claim volume ${volumeChange>=0?"increased":"decreased"} ${Math.abs(volumeChange).toFixed(1)}%`,detail:`${current.length} submitted files versus ${prior.length} in the comparison quarter.`,basis:"Measured from source-quarter file counts."});
 const recovery=averageAdditionalRcv(current).value, priorRecovery=averageAdditionalRcv(prior).value;
 out.push({id:"recovery",severity:recovery&&priorRecovery&&recovery>=priorRecovery?"positive":"info",title:"Average additional RCV movement",detail:recovery&&priorRecovery?`${pct(recovery,priorRecovery)>=0?"+":""}${pct(recovery,priorRecovery).toFixed(1)}% versus the comparison quarter.`:"Unavailable until both periods have usable financial data.",basis:"Uses captured and partially captured financial records only."});
 const cycle=averageCycleTime(current).value, priorCycle=averageCycleTime(prior).value;if(cycle&&priorCycle&&cycle>priorCycle*1.08)out.push({id:"cycle",severity:"warning",title:"Cycle time deterioration",detail:`Average closed-file cycle time is ${(cycle-priorCycle).toFixed(1)} days slower.`,basis:"Measured from recorded open and close dates."});
 const mix=carrierMix(current,carriers);if(mix[0]?.share>35)out.push({id:"carrier",severity:"warning",title:"Carrier concentration",detail:`${mix[0].name} represents ${mix[0].share.toFixed(1)}% of selected files.`,basis:"Share of submitted file count."});
 const coverage=financialCoverage(current).value??0;if(coverage<75)out.push({id:"coverage",severity:"warning",title:"Low financial coverage",detail:`Only ${coverage.toFixed(1)}% of selected files have usable financial data.`,basis:"Captured plus partially captured statuses; missing data is never treated as zero."});
 const stalled=current.filter(c=>c.status==="stalled");if(stalled.length)out.push({id:"stalled",severity:"critical",title:`${stalled.length} stalled files`,detail:`${stalled.filter(c=>daysSinceLastUpdate(c)>21).length} have not been updated in more than 21 days.`,basis:"Status and recorded update timestamps."});
 const old=agingBuckets(current).find(b=>b.label==="90+")?.count??0;if(old)out.push({id:"aging",severity:"warning",title:"Aging risk",detail:`${old} active files have aged beyond 90 days.`,basis:"Days elapsed from opened date to demo as-of date."});
 const states=new Set(current.map(c=>c.state)), priorStates=new Set(prior.map(c=>c.state));const expansion=[...states].filter(s=>!priorStates.has(s));if(expansion.length)out.push({id:"geo",severity:"positive",title:"Geographic expansion",detail:`New selected-period activity in ${expansion.join(", ")}.`,basis:"State presence compared with the prior source quarter."});
 const ids=new Set(current.map(c=>c.id));const matched=matches.filter(m=>ids.has(m.claimId));if(matched.length){const events=new Set(matched.map(m=>m.weatherEventId));out.push({id:"weather",severity:"info",title:"Weather opportunity",detail:`${matched.length} files align with ${events.size} synthetic weather event${events.size===1?"":"s"}.`,basis:`Deterministic ZIP, state, and date-window matches across ${weather.length} demo events.`})}
 return out;
}
