export const clientPortalDemo = {
  asOf: "July 29, 2026",
  health: { score: 92, label: "Excellent", explanation: "Based on activity, staffing, submissions, payment history, and operational trends." },
  partnership: {
    since: "April 2020",
    files: "1,842",
    gains: "$4,832,000",
    fees: "$382,000",
    netValue: "$4,450,000",
    roi: "1,164%",
    impact: ["148 average roofing projects", "Approximately $618 returned per day", "6 years of partnership"],
  },
  weather: { events: 3, type: "High Wind", distance: "17 miles away", zips: 7, roofs: "2,400", branches: 2 },
  recommendations: [
    { priority: "High", title: "Accelerate Raleigh supplements", detail: "Charlotte closes supplements faster than Raleigh.", impact: "$18,000 potential", action: "Review six Raleigh files older than 21 days." },
    { priority: "High", title: "Respond to Wilmington wind activity", detail: "Recent wind activity overlaps your coastal service footprint.", impact: "2,400 estimated roofs", action: "Review nearby claims and branch capacity." },
    { priority: "Medium", title: "Convert inactive estimates", detail: "Three estimates show claim-handling opportunity signals.", impact: "$9,600 potential", action: "Ask account owners to review eligibility." },
    { priority: "Medium", title: "Verify administrator access", detail: "One administrator has not logged in for 61 days.", impact: "Access risk", action: "Complete the one-minute staffing review." },
  ],
  benchmarks: [
    { label: "Files submitted", value: "42 / month", standing: "Above average", tone: "up" },
    { label: "Average supplement", value: "$6,420", standing: "Top quartile", tone: "up" },
    { label: "Claim closure speed", value: "24 days", standing: "Top 10%", tone: "up" },
    { label: "ROI", value: "496%", standing: "Above average", tone: "up" },
    { label: "Estimate conversion", value: "31%", standing: "Below average", tone: "down" },
    { label: "Payment timeliness", value: "96%", standing: "Top quartile", tone: "up" },
  ],
  opportunity: {
    total: "$184,000",
    parts: [
      ["Missed supplements", "$68,000", 37],
      ["Weather opportunity", "$52,000", 28],
      ["Estimate conversion", "$31,000", 17],
      ["Outstanding claims", "$21,000", 11],
      ["Opportunity pipeline", "$12,000", 7],
    ],
  },
  branches: [
    { name: "Charlotte", score: 94, roi: "548%", supplement: "$7,120", files: 26, completion: "91%", trend: "+12%" },
    { name: "Raleigh", score: 84, roi: "412%", supplement: "$5,640", files: 18, completion: "78%", trend: "+4%" },
  ],
  carriers: [
    { name: "North Star Mutual", approval: "5.2 days", supplement: "$7,480", rate: "91%" },
    { name: "Coastal Assurance", approval: "7.8 days", supplement: "$6,210", rate: "86%" },
    { name: "Pioneer Risk", approval: "9.1 days", supplement: "$5,760", rate: "82%" },
  ],
  wins: [
    ["Largest supplement", "$14,500", "State Farm · Charlotte"],
    ["Fastest close", "11 days", "Wind claim · Raleigh"],
    ["Largest monthly gain", "$82,000", "June 2026"],
    ["Highest ROI", "812%", "Commercial hail claim"],
    ["Newest five-star review", "★★★★★", "Charlotte homeowner"],
  ],
  fileDetails: [
    { employee: "Taylor Morgan", days: 18, milestone: "Carrier response", priority: "High" },
    { employee: "Jamie Collins", days: 9, milestone: "Client documents", priority: "Medium" },
    { employee: "Marcus Reed", days: 31, milestone: "Supplement review", priority: "High" },
    { employee: "Danielle Foster", days: 6, milestone: "Estimate delivery", priority: "Normal" },
  ],
  timeline: [
    ["Today", "Taylor completed claim TSI-1001", "Settlement package delivered"],
    ["Yesterday", "North Star approved a supplement", "$7,400 additional RCV"],
    ["Monday", "Weather event detected nearby", "Wilmington wind opportunity"],
    ["Saturday", "Marcus submitted an estimate", "TSI-1003 entered carrier review"],
    ["Thursday", "Staffing review requested", "Pending TotalScope review"],
  ],
  attention: [
    ["2 files waiting", "Carrier response overdue", "Review files"],
    ["3 invoices pending", "Payment confirmation unavailable", "Review billing"],
    ["1 staffing review", "Verification due this month", "Verify team"],
    ["Weather opportunity", "Wind event near Wilmington", "Review opportunity"],
    ["Client follow-up", "Two document requests unanswered", "Contact clients"],
  ],
  industry: [
    ["Material costs", "+2.8%", "Trending upward"],
    ["Hiring trend", "Stable", "Regional labor steady"],
    ["Storm activity", "Elevated", "Southeast wind"],
    ["Regional demand", "+11%", "Month over month"],
    ["Approval trend", "Improving", "1.4 days faster"],
  ],
  prompts: [
    "What should I focus on this week?",
    "Why is Charlotte outperforming Raleigh?",
    "Show weather opportunities nearby.",
    "Which files need attention first?",
    "What is lowering my ROI?",
  ],
} as const;
